import { z } from "zod";
import rateCardJson from "@/data/rate-card.json";

// App-side list prices. The Proposales catalog API exposes no prices, types or units
// (see docs/API_FINDINGS.md), so they live here, keyed by the content library IDs.
// Generated by `npm run seed -- --rate-card`.

export const PRODUCT_CATEGORIES = ["accommodation", "meeting_room", "food_and_beverage", "package", "other"] as const;
export const PRODUCT_UNITS = ["night", "day", "person", "unit"] as const;

export type ProductCategory = (typeof PRODUCT_CATEGORIES)[number];
export type ProductUnit = (typeof PRODUCT_UNITS)[number];

const rateCardEntrySchema = z.object({
  product_id: z.number().int().positive(),
  variation_id: z.number().int().positive(),
  key: z.string().min(1),
  title: z.string().min(1),
  category: z.enum(PRODUCT_CATEGORIES),
  unit: z.enum(PRODUCT_UNITS),
  unitLabel: z.string().min(1).optional(),
  /** Minor units (cents), excluding VAT. */
  unitPrice: z.number().int().nonnegative(),
  vatRate: z.number().min(0).max(1),
});

export const rateCardSchema = z
  .object({
    currency: z.string().length(3),
    vatBasis: z.literal("excluded"),
    priceUnit: z.literal("minor"),
    products: z.array(rateCardEntrySchema),
  })
  .refine((card) => new Set(card.products.map((p) => p.variation_id)).size === card.products.length, {
    message: "Duplicate variation_id in rate card",
  });

export type RateCard = z.infer<typeof rateCardSchema>;
export type RateCardEntry = RateCard["products"][number];

/** Parsed once at module load: an invalid rate card fails fast instead of producing wrong prices. */
export const rateCard: RateCard = rateCardSchema.parse(rateCardJson);
